Document: libpara
Title: Debian libpara Manual
Author: <insert document author here>
Abstract: This manual describes what libpara is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libpara/libpara.sgml.gz

Format: postscript
Files: /usr/share/doc/libpara/libpara.ps.gz

Format: text
Files: /usr/share/doc/libpara/libpara.text.gz

Format: HTML
Index: /usr/share/doc/libpara/html/index.html
Files: /usr/share/doc/libpara/html/*.html
